import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container bg-white min-vh-100 mx-auto my-0 shadow-lg">
            <header className="h-25 fw-bold fs-5 lh-lg">
                <Link href={'/'} className="text-black text-decoration-none">📚 ONEBITE BOOKS</Link>
            </header>
            <main className="pt-3">
                {children}
            </main>
            <footer className="py-5 px-0">제작 @이강혁</footer>
        </div>
        </body>
        </html>
    );
}
